feat: adding log logic to review line onclick on more infos
DISIC/jedonnemonavis.numerique.gouv.fr pull request #203
Opened 2024-10-16 14:23 UTC by BrianRid

2024-10-17 08:09 UTC, ClementNumericite requested changes
Quelques retours

2024-10-17 08:09 UTC, ClementNumericite commented on webapp-backoffice/src/server/routers/reviewViewLog.ts
> +			});
pas besoin, tu peux directement utiliser ctx.session.user.id pour ta requête suivante `existingReviewViewLog`

2024-10-17 08:09 UTC, ClementNumericite commented on webapp-backoffice/src/server/routers/reviewViewLog.ts
> +			return reviewViewLog;
pour respecter le standard sur l'API qu'on a mis en place c'est plutôt
`return { data: reviewViewLog };`

2024-10-17 08:09 UTC, ClementNumericite commented on webapp-backoffice/src/server/routers/reviewViewLog.ts
> +			} else {
1/ ici plutôt retourner l'existing dans ce cas 
`return { data: existingReviewViewLog };`(voir commentaire suivant sur pourquoi `data`

2/ ne pas mettre de else, comme tu return ici, le code continue que si on rentre pas dans le if, donc else non nécessaire, et c'est plus lisible

2024-10-21 22:26 UTC, YoannNumericite approved these changes

2024-10-21 22:30 UTC, merged