feat/accessibility-ara
DISIC/jedonnemonavis.numerique.gouv.fr pull request #204
Opened 2024-10-16 15:56 UTC by FredericNumericite

2024-10-17 08:47 UTC, ClementNumericite requested changes
Couleurs

2024-10-17 08:47 UTC, ClementNumericite commented on webapp-backoffice/src/components/dashboard/Stats/ChartWrapper.tsx
>  	}
utilise les couleurs en variable du DSFR pour les couleurs
https://components.react-dsfr.codegouv.studio/?path=/docs/%F0%9F%8E%A8-color-helper--page

2024-10-17 08:47 UTC, ClementNumericite commented on webapp-backoffice/src/components/dashboard/Stats/ChartWrapper.tsx
>  	}
https://components.react-dsfr.codegouv.studio/?path=/docs/%F0%9F%8E%A8-color-helper--page

2024-11-05 15:04 UTC, YoannNumericite approved these changes

2024-11-05 15:12 UTC, merged